%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/bkossows/Documents/szwedlab/t1w.tsv
%
% Auto-generated by MATLAB on 31-Mar-2021 11:47:16

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 69);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["bids_name", "cjv", "cnr", "efc", "fber", "fwhm_avg", "fwhm_x", "fwhm_y", "fwhm_z", "icvs_csf", "icvs_gm", "icvs_wm", "inu_med", "inu_range", "qi_1", "qi_2", "rpve_csf", "rpve_gm", "rpve_wm", "size_x", "size_y", "size_z", "snr_csf", "snr_gm", "snr_total", "snr_wm", "snrd_csf", "snrd_gm", "snrd_total", "snrd_wm", "spacing_x", "spacing_y", "spacing_z", "summary_bg_k", "summary_bg_mad", "summary_bg_mean", "summary_bg_median", "summary_bg_n", "summary_bg_p05", "summary_bg_p95", "summary_bg_stdv", "summary_csf_k", "summary_csf_mad", "summary_csf_mean", "summary_csf_median", "summary_csf_n", "summary_csf_p05", "summary_csf_p95", "summary_csf_stdv", "summary_gm_k", "summary_gm_mad", "summary_gm_mean", "summary_gm_median", "summary_gm_n", "summary_gm_p05", "summary_gm_p95", "summary_gm_stdv", "summary_wm_k", "summary_wm_mad", "summary_wm_mean", "summary_wm_median", "summary_wm_n", "summary_wm_p05", "summary_wm_p95", "summary_wm_stdv", "tpm_overlap_csf", "tpm_overlap_gm", "tpm_overlap_wm", "wm2max"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "bids_name", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "bids_name", "EmptyFieldRule", "auto");

% Import the data
t1w = readtable("t1w.tsv", opts);


data = table2array(t1w(:,2:end));
list = table2array(t1w(:,1));


%% Clear temporary variables
clear opts