%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/bkossows/Documents/szwedlab/dane/group_bold.tsv
%
% Auto-generated by MATLAB on 31-Mar-2021 12:26:11

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 45);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["bids_name", "aor", "aqi", "dummy_trs", "dvars_nstd", "dvars_std", "dvars_vstd", "efc", "fber", "fd_mean", "fd_num", "fd_perc", "fwhm_avg", "fwhm_x", "fwhm_y", "fwhm_z", "gcor", "gsr_x", "gsr_y", "size_t", "size_x", "size_y", "size_z", "snr", "spacing_tr", "spacing_x", "spacing_y", "spacing_z", "summary_bg_k", "summary_bg_mad", "summary_bg_mean", "summary_bg_median", "summary_bg_n", "summary_bg_p05", "summary_bg_p95", "summary_bg_stdv", "summary_fg_k", "summary_fg_mad", "summary_fg_mean", "summary_fg_median", "summary_fg_n", "summary_fg_p05", "summary_fg_p95", "summary_fg_stdv", "tsnr"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "bids_name", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "bids_name", "EmptyFieldRule", "auto");

% Import the data
bold = readtable("group_bold.tsv", opts);

data = table2array(bold(:,2:end));
list = table2array(bold(:,1));

%% Clear temporary variables
clear opts